### ISSUE TITLE
Build failing on `react-native run-ios` (FIX)

### ISSUE THREAD

**Issue by RohanVB** [wevote/WeVoteReactNative#17]
On further investigation, it should ideally work by this fix: https://github.com/facebook/react-native/issues/8584#issuecomment-236366222

If you're still getting an error related to `Ignoring return value of function declared with warn_unused_result attribute` as I was on OSX Sierra, you may have to do this: https://yanqiw.github.io/2016/10/05/react-native-adopt-to-xcode8.html also.

**Comment by DaleMcGrew** [comment]
Hi @RohanVB this will save someone else some time! Thank you. Would you be open to adding this to this documentation page? https://github.com/wevote/WeVoteReactNative/blob/master/docs/installing/RUNNING_FIRST_TIME.md
