### ISSUE TITLE
Can you help us set up cookies for Android?

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteReactNative#50]
We are trying to figure out how to "set" and "get" simple cookies on Android. Can you help @jainanisha90 set this up?

**Comment by RohanVB** [comment]
One thing I've come across is that the cookies for react-native  projects are internally handled (objC code) and if we need to manipulate the javascript code, that's when the `react-native-cookies` package comes into play.
This led me to believe that it may not be necessary to use that package.

**Other important links:** 

https://stackoverflow.com/questions/41132167/react-native-fetch-cookie-persist
https://github.com/github/fetch#sending-cookies

**Comment by SailingSteve** [comment]
There's two of these
react-native-cookie      https://github.com/shimohq/react-native-cookie
and
react-native-cookies     https://github.com/joeferraro/react-native-cookies

**Comment by SailingSteve** [comment]
Not sure this will be the solution we go for long term, but it works fine in Android and iOS.
