### ISSUE TITLE
Twitter Login: Android and iOS

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteReactNative#51]
We are looking for someone with experience using Twitter Kit (or similar system) so we can sign into our ReactNative app on Android and iOS. Please let dale.mcgrew@WeVote.US know if you can help!

https://dev.twitter.com/twitterkit/android/log-in-with-twitter

Many thanks.

**Comment by SailingSteve** [comment]
The oAuth part works on both Android and iOS.  We successfully login in to WeVote.  There is still some more to do with post-login work like voterMergeTwoAccountsByTwitterKey to make sure it is fully working, and some other edge case processing.

**Comment by DaleMcGrew** [comment]
Verified. Thank you @SailingSteve!
