### ISSUE TITLE
Some components similar to webapp can be replicating using Lightbox

### ISSUE THREAD

**Issue by RohanVB** [wevote/WeVoteReactNative#55]
https://github.com/oblador/react-native-lightbox

eg. 
![screen shot 2017-07-30 at 8 18 58 pm](https://user-images.githubusercontent.com/15197846/28754514-6f072ae2-7564-11e7-948d-979c65d18af5.png)

**Comment by DaleMcGrew** [comment]
This is a great suggestion for a component we can use. Closing as an issue.
