### ISSUE TITLE
Async usage?

### ISSUE THREAD

**Issue by pertrai1** [wevote/WeVoteReactNative#8]
I saw that `async` is being used. Is this coming from React Native? 

https://github.com/wevote/WeVoteReactNative/blob/master/index.ios.js#L43

**Comment by DaleMcGrew** [comment]
async is working for us! We will want to rethink how we bring in data, and how we trigger requests for more information from the API Server, but I feel really good about what we have working so far. @Jayadev6191 & @colettephair did great work this weekend!

**Comment by pertrai1** [comment]
Yes you all should feel very good about what you were able to accomplish over the weekend. I was not sure about how `async` is being used without the `async` node api. No issue, just a question I had as I was looking at some code briefly.
